package uk.co.gdickinson.smarthome.lambda.models;

public enum ErrorType {

    ALREADY_IN_OPERATION,
    BRIDGE_UNREACHABLE,
    ENDPOINT_BUSY,
    ENDPOINT_LOW_POWER,
    ENDPOINT_UNREACHABLE,
    EXPIRED_AUTHORIZATION_CREDENTIAL,
    FIRMWARE_OUT_OF_DATE,
    HARDWARE_MALFUNCTION,
    INTERNAL_ERROR,
    INVALID_AUTHORIZATION_CREDENTIAL,
    INVALID_DIRECTIVE,
    INVALID_VALUE,
    NO_SUCH_ENDPOINT,
    NOT_SUPPORTED_IN_CURRENT_MODE,
    NOT_IN_OPERATION,
    POWER_LEVEL_NOT_SUPPORTED,
    RATE_LIMIT_EXCEEDED,
    TEMPERATURE_VALUE_OUT_OF_RANGE,
    VALUE_OUT_OF_RANGE
}
